app/models/instrument.rb
app/models/user.rb
db/migrate/20200817140250_create_instruments.rb
db/schema.rb
test/models/instrument_test.rb

instrument model created

---

app/controllers/instruments_controller.rb
app/views/instruments/create.html.erb
app/views/instruments/destroy.html.erb
app/views/instruments/edit.html.erb
app/views/instruments/index.html.erb
app/views/instruments/new.html.erb
app/views/instruments/show.html.erb
app/views/instruments/update.html.erb
config/routes.rb
test/controllers/instruments_controller_test.rb

Generated Controller for instruments.
Routes created.
Index view created

generated instruments controller

---

app/assets/config/manifest.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
config/application.rb

Basic front end

---

app/controllers/instruments_controller.rb
app/models/instrument.rb
app/models/user.rb

Instrument controller update (define all methods for the crud)
Instrument model presence validation on all attributes (except description)

updated instrument controller and validation on instrument model

---

Gemfile
Gemfile.lock
db/migrate/20200817161450_add_username_to_users.rb
db/schema.rb
db/seeds.rb

Add username to the USers table created by devise.
Implement code to create Users and Instruments in db/seeds.rb

add username to users table, modify seeds file

---

config/initializers/devise.rb

 mail contact changed

---

db/migrate/20200818112723_add_title_to_instruments.rb
db/schema.rb

Add title column to instruments

add title to instruments

---

app/controllers/instruments_controller.rb
app/views/instruments/new.html.erb

take the front end style of sensible men to the create form instrument.

create instrument style

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_index.scss
app/views/instruments/index.html.erb
app/views/instruments/new.html.erb
app/views/shared/_footer.html.erb

Styling index

---

app/controllers/dashboards_controller.rb
app/controllers/instruments_controller.rb
app/views/dashboards/summary.html.erb

changed create method on instruments controller

changed create method on instruments controller

---

app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_carousel.scss
app/views/instruments/show.html.erb

Show continuing

---

app/views/devise/sessions/new.html.erb

login modification

---

app/controllers/instruments_controller.rb
app/views/dashboards/summary.html.erb
app/views/instruments/new.html.erb

Updated Dashboard controller and views to display details to owners and users
Updated instruments controller to permit title and added in the form to create new instruments to rent

Dashboard controller update

---

app/controllers/bookings_controller.rb
app/models/booking.rb
db/migrate/20200819112407_add_status_to_bookings.rb
db/schema.rb

added status column to bookings
validation to include only accepted, pending, declined

added status column to bookings

---

app/controllers/instruments_controller.rb
app/views/dashboards/summary.html.erb
app/views/instruments/_form.html.erb

add edit button

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_navbar.scss
app/javascript/plugins/init_mapbox.js
app/views/dashboards/summary.html.erb
app/views/instruments/index.html.erb

Cards links

---

app/javascript/plugins/init_autocomplete.js
app/views/instruments/new.html.erb

did instruments/new form

---

db/seeds.rb

updated seeds with more relevant info

updated seeds with more relevant info

---

app/controllers/instruments_controller.rb
app/views/dashboards/summary.html.erb
app/views/instruments/index.html.erb
app/views/instruments/new.html.erb
app/views/instruments/show.html.erb
config/environments/production.rb
db/seeds.rb

cloudinary on index, show and dsahboard
seeds quick update
deleted carroussel from show (no front work aside a quick display flex)

implement cloudinary

---

app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/javascript/plugins/init_mapbox.js
app/views/instruments/_info_window.html.erb

change autocomplete file with  instrument_pickup_address
and add map.addControl  to init.mapbox

fix autocomplete geocoder

---

app/controllers/instruments_controller.rb
app/views/instruments/show.html.erb
app/views/shared/_booking.html.erb

add booking form on show (en mode degueulasse et ca marche pas encore - surement on aura besoin du ajax du cours de vendredi)

add booking form on show

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_tabs.scss
app/views/dashboards/summary.html.erb
app/views/instruments/_form.html.erb
app/views/instruments/_info_window.html.erb
app/views/instruments/index.html.erb
app/views/instruments/new.html.erb
app/views/instruments/show.html.erb
db/seeds.rb

Dashboard + edit form

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/models/booking.rb
app/models/instrument.rb
app/views/instruments/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_booking_form.html.erb

card validation try + searh dropdown on home page

---

app/assets/stylesheets/application.scss
app/controllers/dashboards_controller.rb
app/javascript/packs/application.js
app/views/dashboards/summary.html.erb

Booking dashboard overview
Show requests, bookings sent and history.
Need to code the write a review on the past history bookings and make the buttons to change the request status

Dashboard bookings update

---

app/views/shared/_navbar.html.erb

Add Sign Up in order to Sign In in the navbar

---

app/controllers/instruments_controller.rb
app/views/dashboards/summary.html.erb

fixing button position on dashbaord + black logo in map
